//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsMultiLangSample.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsMultiLangSample.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Switch to English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnEnglish {
            get {
                return ResourceManager.GetString("BtnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnJapanese {
            get {
                return ResourceManager.GetString("BtnJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change &quot;Localizable&quot; properties &quot;True&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label1_text {
            get {
                return ResourceManager.GetString("label1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change &quot;Langage&quot; property &quot;日本語&quot; temporary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label2_text {
            get {
                return ResourceManager.GetString("label2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language changes will take effect after restarting the application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgRestartRequired {
            get {
                return ResourceManager.GetString("MsgRestartRequired", resourceCulture);
            }
        }
    }
}
